name: Serverless CD Workflow
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: zombieland-dev
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - name: actions/setup-node@v1
      with:
        node-version: 17.9.0
    - name: Build serverless functions
      run: make build
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
